### ISSUE TITLE
Error applying state vim.extended_config: missing parent directory

### ISSUE THREAD

**Issue by binary-sequence** [binary-sequence/salt-states#1]
```
----------
          ID: vim.extended_config
    Function: file.managed
        Name: /etc/binary-sequence/vimrc
      Result: False
     Comment: Parent directory not present
     Started: 22:06:20.417950
    Duration: 184.064 ms
     Changes:
----------
```
